services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pipenv install --deploy --ignore-pipfile
    startCommand: pipenv run gunicorn myapp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myapp.settings
      - key: DATABASE_URL
        fromDatabase:
          name: my-mysql-database
          property: connectionString
      - key: SECRET_KEY
        sync: false
        value: "your-secret-key"
      - key: ALLOWED_HOSTS
        value: "https://tynuevbatteryswapmanager.onrender.com"

databases:
  - name: my-mysql-database
    type: mysql
    plan: free
    version: 8.0
    settings:
      max_connections: 100
      default_transaction_isolation: READ COMMITTED
      character_set_server: utf8mb4
      collation_server: utf8mb4_unicode_ci

# Optional: Specify static files if needed
staticFiles:
  - src: /static
    dest: /static

# Optional: Specify additional files to be included in the deployment
includeFiles:
  - path: .env
