services:
  - type: web
    name: tynuev
    env: python
    buildCommand: pipenv install --deploy --ignore-pipfile && pipenv run python manage.py collectstatic --noinput
    startCommand: pipenv run gunicorn tynuev.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tynuev.settings
      - key: DATABASE_URL
        fromDatabase:
          name: tynuev_db
          property: connectionString
      - key: SECRET_KEY
        sync: false
        value: "TYNUEV_PROJECT"
      - key: ALLOWED_HOSTS
        value: "tynuev.onrender.com"
    staticPublishPath: /staticfiles

databases:
  - name: tynuev_db
    type: mysql
    plan: free
    version: 8.0
    settings:
      max_connections: 100
      default_transaction_isolation: READ COMMITTED
      character_set_server: utf8mb4
      collation_server: utf8mb4_unicode_ci
