services:
  - type: database
    name: tynuev_db
    plan: free
    version: 8.0
    settings:
      max_connections: 100
      default_transaction_isolation: READ COMMITTED
      character_set_server: utf8mb4
      collation_server: utf8mb4_unicode_ci
