# Generated by Django 4.2.14 on 2024-07-11 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('battery_model', models.CharField(max_length=100)),
                ('battery_serial_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_model', models.CharField(max_length=100)),
                ('bike_serial_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rider_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('complexion', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number_alternate', models.CharField(blank=True, max_length=15, null=True)),
                ('permanent_home_address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='s/pictures/')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='s/headshots/')),
                ('s_card', models.ImageField(blank=True, null=True, upload_to='s/cards/')),
                ('government_id', models.ImageField(blank=True, null=True, upload_to='s/government_ids/')),
                ('proof_of_residency', models.ImageField(blank=True, null=True, upload_to='s/proofs_of_residency/')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_companies', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_deliveries_per_day', models.IntegerField()),
                ('avg_weekly_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('kilometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.rider')),
            ],
        ),
        migrations.CreateModel(
            name='KinGuarantorInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('next_of_kin_home_address', models.TextField(blank=True, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_passport', models.ImageField(blank=True, null=True, upload_to='kin/next_of_kin_passports/')),
                ('guarantor_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('guarantor_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('guarantor_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('guarantor_home_address', models.TextField(blank=True, null=True)),
                ('guarantor_profession', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_id', models.ImageField(blank=True, null=True, upload_to='kin/guarantor_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kin_guarantor_info', to='records.rider')),
            ],
        ),
    ]
