# Generated by Django 4.2.14 on 2024-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ODO',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='kilometer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
        ),
    ]
