# Generated by Django 4.2.14 on 2024-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_battery_record_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtracker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
