# Generated by Django 4.2.14 on 2024-07-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_idtracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtracker',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
